-- ============================================================
-- 030: Public five-character profile lookup codes
-- Codes are generated by the database, never accepted from clients.
-- ============================================================

alter table public.profiles
  add column if not exists user_code text;

create or replace function public.generate_user_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  loop
    candidate := upper(substr(encode(gen_random_bytes(5), 'hex'), 1, 5));
    exit when not exists (select 1 from public.profiles where user_code = candidate);
  end loop;
  return candidate;
end;
$$;

alter table public.profiles
  alter column user_code set default public.generate_user_code();

update public.profiles
set user_code = public.generate_user_code()
where user_code is null or user_code !~ '^[A-Z0-9]{5}$';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.profiles'::regclass and conname = 'profiles_user_code_key'
  ) then
    alter table public.profiles add constraint profiles_user_code_key unique (user_code);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.profiles'::regclass and conname = 'profiles_user_code_format'
  ) then
    alter table public.profiles add constraint profiles_user_code_format
      check (user_code ~ '^[A-Z0-9]{5}$');
  end if;
end $$;

create index if not exists profiles_user_code_idx on public.profiles (user_code);
